[package]
name = "cedar"
version = "0.1.0"
edition = "2021"

[dependencies]
cedar-policy = { version = "2.4.5" }
thiserror = "1.0.58"
once_cell = "1.17.1"
serde = "1.0.108"

[lib]
crate_type = ["cdylib"]

[profile.release]
strip = "debuginfo"